export { Home } from "./home"
export { About } from "./about"
export { Projects } from "./projects"
export { Skills } from "./skills"
export { Contact } from "./contact"
export { Footer } from "./footer"